# ??? SERVER ???????????????????????????????????????????????
server.port=${PORT:8080}

# ??? CORS ?????????????????????????????????????????????????
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# ??? MAIL (Brevo SMTP) ????????????????????????????????????
spring.mail.host=${SPRING_MAIL_HOST:smtp-relay.brevo.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mail.from=${MAIL_FROM:noreply@example.com}
mail.to=${MAIL_TO:andrea.fumero@humanitas.it}
mail.iban=${MAIL_IBAN:IT54D0358901600010570777717}

# ??? LOGGING ??????????????????????????????????????????????
logging.level.com.fumero=INFO
logging.level.org.springframework.mail=DEBUG

# ?? RESEND API
resend.api.key=${RESEND_API_KEY:}
